import { CalendarDays, ExternalLink, FileText, Instagram, Link2, MessageCircle, Send } from "lucide-react";
import { ShareLinkButton } from "@/components/tools/share-link-button";

type Hub = { slug: string; title: string; bio: string | null; owner_name?: string | null; floor_number?: number | null };
type Item = { id: string; title: string; url: string; description: string | null; icon: "link" | "form" | "instagram" | "document" | "calendar" | "contact" };
const icons = { link: Link2, form: Send, instagram: Instagram, document: FileText, calendar: CalendarDays, contact: MessageCircle };

export function LinkHubView({ hub, items }: { hub: Hub; items: Item[] }) {
  return <div className="mx-auto max-w-xl"><header className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-primary/[0.16] via-card to-sky-400/10 p-6 text-center shadow-card sm:p-8"><div className="absolute -right-8 -top-10 h-36 w-36 rounded-full bg-primary/10 blur-2xl" /><span className="relative mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-primary text-xl font-black text-primary-foreground shadow-lg">W</span><h1 className="relative mt-4 text-2xl font-extrabold tracking-tight">{hub.title}</h1>{hub.bio && <p className="relative mx-auto mt-2 max-w-md text-sm leading-relaxed text-muted-foreground">{hub.bio}</p>}<p className="relative mt-3 text-xs font-semibold text-primary">{hub.owner_name ?? "WISH RA"}{hub.floor_number ? ` · ${hub.floor_number}F` : ""}</p><div className="relative mt-4 flex justify-center"><ShareLinkButton title={hub.title} path={`/links/${hub.slug}`} /></div></header><main className="mt-4 space-y-3">{items.map((item) => { const Icon = icons[item.icon] ?? Link2; return <a key={item.id} href={item.url} target="_blank" rel="noopener noreferrer" className="group flex items-center gap-3 rounded-2xl border border-border bg-card p-3.5 shadow-sm transition-transform active:scale-[0.98]"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="h-5 w-5" /></span><span className="min-w-0 flex-1"><span className="block truncate font-bold">{item.title}</span>{item.description && <span className="mt-0.5 block truncate text-xs text-muted-foreground">{item.description}</span>}</span><ExternalLink className="h-4 w-4 shrink-0 text-muted-foreground" /></a>; })}{items.length === 0 && <div className="rounded-2xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">表示中のリンクはありません</div>}</main><footer className="py-8 text-center text-[10px] font-semibold tracking-[0.16em] text-muted-foreground">WISH EVENTS · RESIDENT TOOLS</footer></div>;
}
